apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "daps-reg-service.fullname" . }}
  labels:
    {{- include "daps-reg-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "daps-reg-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "daps-reg-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "daps-reg-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
          - name: APP_DAPS_CLIENTID
            value: "admin"
          - name: APP_DAPS_CLIENTSECRET
            value: "secret@catenax!"
          - name: KEYCLOACK_AUTH-SERVER-URL
            value: "https://centralidp.demo.catena-x.net/auth"
          - name: KEYCLOACK_REALM
            value: "CX-Central"
          - name: KEYCLOACK_RESOURCE
            value: "sa3"
          - name: APP_DAPS_APIURI
            value: "https://daps-pen.int.demo.catena-x.net/api/v1"
          - name: APP_DAPS_TOKENURI
            value: "https://daps-pen.int.demo.catena-x.net/token"
                
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
