keycloak:
  #auth-server-url:
  #realm:
  #resource:
  bearer-only: true
  use-resource-role-mappings: true
  principal-attribute: preferred_username
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /DapsRegApi.yaml
app:
  build:
    version: ^project.version^
  daps:
    #apiUri:
    #tokenUri:
    #clientId:
    #clientSecret:
  security:
    createRole: create_daps_client
    updateRole: update_daps_client
    deleteRole: delete_daps_client
    retrieveRole: retrieve_daps_client
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: *
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:
  lifecycle:
    timeout-per-shutdown-phase: 30s
logging:
  level:
    org:
      springframework:
        security:
          web:
            csrf: INFO
