keycloak:
  #auth-server-url:
  #realm:
  #resource:
  bearer-only: true
  use-resource-role-mappings: true
  principal-attribute: preferred_username
app:
  build:
    version: ^project.version^
  daps:
    #apiUri:
    #tokenUri:
    #clientId:
    #clientSecret:
  security:
    createRole: create_daps_client
    updateRole: update_daps_client
    deleteRole: delete_daps_client
