keycloak:
  auth-server-url: https://keycloak.cx.dih-cloud.com
  realm: orchestrator
  resource: orchestratorservice
  bearer-only: true
  use-resource-role-mappings: true
  principal-attribute: preferred_username
app:
  build:
    version: ^project.version^
  daps:
    apiUri: https://daps-pen.int.demo.catena-x.net/api/v1
    tokenUri: https://daps-pen.int.demo.catena-x.net/token
    clientId: 
    clientSecret:
  security:
    createRole: add_self_descriptions
    updateRole: update_daps_client
    deleteRole: delete_daps_client
